run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: github-actions

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gosimple
    - ineffassign
    - typecheck
    - errcheck
    - gosec
