// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/presentation/grpc/service.proto

package warehousev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfo            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItemRequest) Reset() {
	*x = ReserveItemRequest{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItemRequest) ProtoMessage() {}

func (x *ReserveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItemRequest.ProtoReflect.Descriptor instead.
func (*ReserveItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveItemRequest) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReleaseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemInfo            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseItemRequest) Reset() {
	*x = ReleaseItemRequest{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseItemRequest) ProtoMessage() {}

func (x *ReleaseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseItemRequest.ProtoReflect.Descriptor instead.
func (*ReleaseItemRequest) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{1}
}

func (x *ReleaseItemRequest) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAllItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsResponse) Reset() {
	*x = GetAllItemsResponse{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsResponse) ProtoMessage() {}

func (x *GetAllItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Product       *Product               `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *Item) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Item) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Item) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ItemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *ItemInfo) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ItemInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProductResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *Product) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,3,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *UploadImageRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UploadImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadImageRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetImageRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*GetImageResponse_Info
	//	*GetImageResponse_ChunkData
	Data          isGetImageResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetImageResponse) GetData() isGetImageResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetImageResponse) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.Data.(*GetImageResponse_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *GetImageResponse) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*GetImageResponse_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isGetImageResponse_Data interface {
	isGetImageResponse_Data()
}

type GetImageResponse_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type GetImageResponse_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*GetImageResponse_Info) isGetImageResponse_Data() {}

func (*GetImageResponse_ChunkData) isGetImageResponse_Data() {}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_presentation_grpc_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_internal_presentation_grpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *ImageInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_internal_presentation_grpc_service_proto protoreflect.FileDescriptor

const file_internal_presentation_grpc_service_proto_rawDesc = "" +
	"\n" +
	"(internal/presentation/grpc/service.proto\x12\fwarehouse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"B\n" +
	"\x12ReserveItemRequest\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.warehouse.v1.ItemInfoR\x05items\"B\n" +
	"\x12ReleaseItemRequest\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.warehouse.v1.ItemInfoR\x05items\"?\n" +
	"\x13GetAllItemsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.warehouse.v1.ItemR\x05items\"\x80\x01\n" +
	"\x04Item\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12/\n" +
	"\aproduct\x18\x03 \x01(\v2\x15.warehouse.v1.ProductR\aproduct\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"?\n" +
	"\bItemInfo\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"@\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"6\n" +
	"\x15CreateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x88\x01\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x124\n" +
	"\acreated\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\"u\n" +
	"\x12UploadImageRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x03 \x01(\fR\tchunkData\"0\n" +
	"\x0fGetImageRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"j\n" +
	"\x10GetImageResponse\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x17.warehouse.v1.ImageInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\".\n" +
	"\tImageInfo\x12!\n" +
	"\fcontent_type\x18\x01 \x01(\tR\vcontentType2\xe9\x01\n" +
	"\vItemService\x12G\n" +
	"\vReserveItem\x12 .warehouse.v1.ReserveItemRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\vReleaseItem\x12 .warehouse.v1.ReleaseItemRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\vGetAllItems\x12\x16.google.protobuf.Empty\x1a!.warehouse.v1.GetAllItemsResponse2j\n" +
	"\x0eProductService\x12X\n" +
	"\rCreateProduct\x12\".warehouse.v1.CreateProductRequest\x1a#.warehouse.v1.CreateProductResponse2\xad\x01\n" +
	"\x13ProductImageService\x12I\n" +
	"\vUploadImage\x12 .warehouse.v1.UploadImageRequest\x1a\x16.google.protobuf.Empty(\x01\x12K\n" +
	"\bGetImage\x12\x1d.warehouse.v1.GetImageRequest\x1a\x1e.warehouse.v1.GetImageResponse0\x01B2Z0warehouse/internal/presentation/grpc;warehousev1b\x06proto3"

var (
	file_internal_presentation_grpc_service_proto_rawDescOnce sync.Once
	file_internal_presentation_grpc_service_proto_rawDescData []byte
)

func file_internal_presentation_grpc_service_proto_rawDescGZIP() []byte {
	file_internal_presentation_grpc_service_proto_rawDescOnce.Do(func() {
		file_internal_presentation_grpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_presentation_grpc_service_proto_rawDesc), len(file_internal_presentation_grpc_service_proto_rawDesc)))
	})
	return file_internal_presentation_grpc_service_proto_rawDescData
}

var file_internal_presentation_grpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_presentation_grpc_service_proto_goTypes = []any{
	(*ReserveItemRequest)(nil),    // 0: warehouse.v1.ReserveItemRequest
	(*ReleaseItemRequest)(nil),    // 1: warehouse.v1.ReleaseItemRequest
	(*GetAllItemsResponse)(nil),   // 2: warehouse.v1.GetAllItemsResponse
	(*Item)(nil),                  // 3: warehouse.v1.Item
	(*ItemInfo)(nil),              // 4: warehouse.v1.ItemInfo
	(*CreateProductRequest)(nil),  // 5: warehouse.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 6: warehouse.v1.CreateProductResponse
	(*Product)(nil),               // 7: warehouse.v1.Product
	(*UploadImageRequest)(nil),    // 8: warehouse.v1.UploadImageRequest
	(*GetImageRequest)(nil),       // 9: warehouse.v1.GetImageRequest
	(*GetImageResponse)(nil),      // 10: warehouse.v1.GetImageResponse
	(*ImageInfo)(nil),             // 11: warehouse.v1.ImageInfo
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_internal_presentation_grpc_service_proto_depIdxs = []int32{
	4,  // 0: warehouse.v1.ReserveItemRequest.items:type_name -> warehouse.v1.ItemInfo
	4,  // 1: warehouse.v1.ReleaseItemRequest.items:type_name -> warehouse.v1.ItemInfo
	3,  // 2: warehouse.v1.GetAllItemsResponse.items:type_name -> warehouse.v1.Item
	7,  // 3: warehouse.v1.Item.product:type_name -> warehouse.v1.Product
	12, // 4: warehouse.v1.Product.created:type_name -> google.protobuf.Timestamp
	11, // 5: warehouse.v1.GetImageResponse.info:type_name -> warehouse.v1.ImageInfo
	0,  // 6: warehouse.v1.ItemService.ReserveItem:input_type -> warehouse.v1.ReserveItemRequest
	1,  // 7: warehouse.v1.ItemService.ReleaseItem:input_type -> warehouse.v1.ReleaseItemRequest
	13, // 8: warehouse.v1.ItemService.GetAllItems:input_type -> google.protobuf.Empty
	5,  // 9: warehouse.v1.ProductService.CreateProduct:input_type -> warehouse.v1.CreateProductRequest
	8,  // 10: warehouse.v1.ProductImageService.UploadImage:input_type -> warehouse.v1.UploadImageRequest
	9,  // 11: warehouse.v1.ProductImageService.GetImage:input_type -> warehouse.v1.GetImageRequest
	13, // 12: warehouse.v1.ItemService.ReserveItem:output_type -> google.protobuf.Empty
	13, // 13: warehouse.v1.ItemService.ReleaseItem:output_type -> google.protobuf.Empty
	2,  // 14: warehouse.v1.ItemService.GetAllItems:output_type -> warehouse.v1.GetAllItemsResponse
	6,  // 15: warehouse.v1.ProductService.CreateProduct:output_type -> warehouse.v1.CreateProductResponse
	13, // 16: warehouse.v1.ProductImageService.UploadImage:output_type -> google.protobuf.Empty
	10, // 17: warehouse.v1.ProductImageService.GetImage:output_type -> warehouse.v1.GetImageResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_presentation_grpc_service_proto_init() }
func file_internal_presentation_grpc_service_proto_init() {
	if File_internal_presentation_grpc_service_proto != nil {
		return
	}
	file_internal_presentation_grpc_service_proto_msgTypes[10].OneofWrappers = []any{
		(*GetImageResponse_Info)(nil),
		(*GetImageResponse_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_presentation_grpc_service_proto_rawDesc), len(file_internal_presentation_grpc_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_internal_presentation_grpc_service_proto_goTypes,
		DependencyIndexes: file_internal_presentation_grpc_service_proto_depIdxs,
		MessageInfos:      file_internal_presentation_grpc_service_proto_msgTypes,
	}.Build()
	File_internal_presentation_grpc_service_proto = out.File
	file_internal_presentation_grpc_service_proto_goTypes = nil
	file_internal_presentation_grpc_service_proto_depIdxs = nil
}
